project_id = "holbawpbwvnqrkmyearx"

[functions.elevenlabs-stt]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.voice-assistant]
verify_jwt = false
